apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc_name }} 
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.postgres.pvc.accessMode }} 

  storageClassName: {{ .Values.postgres.pvc.storageClassName }} 

  resources:
    requests:
      storage: {{ .Values.postgres.pvc.size }} # e.g., "5Gi"
