replicaCount: 1
image:
  registry: santiagoparraga
  tag: 1
service:
  type: ClusterIP
microserviceA:
  image: "{{ .Values.image.registry }}/microservicea:{{ .Values.image.tag }}"
  port: 8080
microserviceB:
  image: "{{ .Values.image.registry }}/microserviceb:{{ .Values.image.tag }}"
  port: 8081
htmlServer:
  image: "{{ .Values.image.registry }}/htmlserver:{{ .Values.image.tag }}"
  port: 80
postgres:
  image: postgres:15
  user: postgres
  password: postgres
  db: mydb
