replicaCount: 1
image:
  registry: santiagoparraga
  tag: 1
service:
  type: ClusterIP
microserviceA:
  image: "santiagoparraga/microservicea:37"
  port: 8080
microserviceB:
  image: "santiagoparraga/microserviceb:37"
  port: 8081
htmlServer:
  image: "santiagoparraga/htmlserver:37"
  port: 8080
postgres:
  image: postgres:15
  user: postgres
  password: postgres
  db: mydb
  pvc_name: postgres-data-claim
  pvc:
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClassName: gp3
