replicaCount: 1
image:
  registry: santiagoparraga
  tag: 1
service:
  type: ClusterIP
microserviceA:
  image: "santiagoparraga/microservicea:30"
  port: 8080
microserviceB:
  image: "santiagoparraga/microserviceb:30"
  port: 8081
htmlServer:
  image: "santiagoparraga/htmlserver:30"
  port: 80
postgres:
  image: postgres:15
  user: postgres
  password: postgres
  db: mydb
  pvc_name: postgres-data-claim
  pvc:
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClassName: gp3
